language: generic
env:
  global:
  - IDE_VERSION=1.8.1
  - ESP_HOME=$HOME/ide/hardware/esp8266com
  - LIB_HOME=$HOME/Arduino/libraries
  - ESPS_HOME=$HOME/Arduino/ESPixelStick
  - BUILD=$HOME/build
  - DIST=$ESPS_HOME/dist
  - STAMP=$(date +'%Y%m%d%H%M%S')
  - DIST_FILE=ESPixelStick_TRAVIS-$STAMP.zip
before_install:
- wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
- tar xf arduino-$IDE_VERSION-linux64.tar.xz
- mv arduino-$IDE_VERSION $HOME/ide
- export PATH="$HOME/ide:$PATH"
- mkdir -p $LIB_HOME
- mkdir -p $ESP_HOME
- mkdir -p $BUILD
- git clone --recurse-submodules -j8 https://github.com/esp8266/Arduino.git $ESP_HOME/esp8266
- cd $ESP_HOME/esp8266/tools
- python get.py
- git clone https://github.com/bblanchon/ArduinoJson $LIB_HOME/ArduinoJson
- git clone https://github.com/forkineye/ESPAsyncE131 $LIB_HOME/ESPAsyncE131
- git clone https://github.com/me-no-dev/ESPAsyncTCP $LIB_HOME/ESPAsyncTCP
- git clone https://github.com/me-no-dev/ESPAsyncUDP $LIB_HOME/ESPAsyncUDP
- git clone https://github.com/me-no-dev/ESPAsyncWebServer $LIB_HOME/ESPAsyncWebServer
- git clone https://github.com/marvinroger/async-mqtt-client $LIB_HOME/async-mqtt-client
install:
- cp -r $TRAVIS_BUILD_DIR $ESPS_HOME
- arduino --board esp8266com:esp8266:generic:xtal=160,vt=flash,exception=disabled,ResetMethod=nodemcu,CrystalFreq=26,FlashFreq=40,FlashMode=dio,eesz=1M128,led=2,ip=hb2f,dbg=Disabled,lvl=None____,wipe=none,baud=115200
  --pref build.path=$BUILD --save-prefs
before_script:
- cd $ESPS_HOME
- npm install -g gulp-cli
- npm install
script:
- echo "#define ESPS_MODE_PIXEL" > $ESPS_HOME/Mode.h
- arduino --verify $ESPS_HOME/ESPixelStick.ino
- mv $BUILD/ESPixelStick.ino.bin $DIST/firmware/pixel-travis.bin
- echo "#define ESPS_MODE_SERIAL" > $ESPS_HOME/Mode.h
- arduino --verify $ESPS_HOME/ESPixelStick.ino
- mv $BUILD/ESPixelStick.ino.bin $DIST/firmware/serial-travis.bin
- gulp
- gulp md
- gulp travis
- mv $ESPS_HOME/data $DIST/spiffs
- mv $ESPS_HOME/travis/firmware.json $DIST/firmware/firmware.json
- cd $DIST
- zip -r $HOME/$DIST_FILE *
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  user: "MartinMueller2003"
  password: "FartManPoo@03"
  name: ESPixelStick Unify Development Firmware (Travis-CI build - NOT TESTED)
  body: This release includes binaries which were automatically built by Travis-CI and should not be considered stable.
  prerelease: true
  file: $HOME/$DIST_FILE
  skip_cleanup: true
  on:
    repo: MartinMueller2003/ESPixelStick
    branch: unify
